### ISSUE TITLE
Url parameters with inline regex condition

### ISSUE THREAD

**Issue by vizo** [alubbe/named-routes#11]
Express >= 4.12 is capable of param conditions like /:locale(en)/.
But built (url) function is parsing as /en(en).

Any idea how to solve this?

Thanks in advance!

**Comment by vizo** [comment]
Quick fix is to replace build path with  path.replace(/(\(.*\))/g, '');

What do you think?

**Comment by alubbe** [comment]
Thanks for reporting!
I think it would be smarter to re-use express own logic. Could you try using the current master to see if this fixes your problem?
```bash
npm install alubbe/named-routes#e76afc9fe8ffa9c1f35c7a020f1635f3bf165e2d
```

**Comment by vizo** [comment]
Sorry for current project i already moved from Express to Hapi. I will try it next time.

**Comment by alubbe** [comment]
Ah that's too bad. If you still have the code from 3 days ago, it would be great if you could give me feedback if it works for you. I wrote a test case that comes back green, and if you could confirm that it works for you too, I would release this patch to npm.

**Comment by alubbe** [comment]
Closing this due to its age - feel free to reopen this if it's not solved.
