### ISSUE TITLE
ajax route building

### ISSUE THREAD

**Issue by RamyRais** [alubbe/named-routes#14]
I have this URL '/doctors/:speciality/:governorate' and when i write `server.namedRoutes.build('search.doctor', { speciality: null, governorate: null});`

i get this error 
throw new TypeError('Expected "' + token.name + '" to be defined')
          ^

TypeError: Expected "speciality" to be defined

**Comment by RamyRais** [comment]
after investigation since you make generate using the path-to-regexp, the null stuff for creating ajax route don't work anymore.
```
if(this.expressMode) {
  route.generate = require("path-to-regexp").compile(path);
}
```

**Comment by alubbe** [comment]
Thanks for reporting!
I will try to take a look at it next week - or if you are interested, 
you are welcome to contribute a PR (even just a failing test case would 
be helpful).
Have a great weekend!

**Comment by RamyRais** [comment]
yes i did a workaround for it you can take a look at my [fork](https://github.com/RamyRais/named-routes) for last commits. i am trying also to fix the other problem when using express.Router()

**Comment by alubbe** [comment]
Your issue should be resolved by the latest commit.
Have a look at these test cases to check if they reflect your usage:
https://github.com/alubbe/named-routes/commit/85c5ef1fe4ecf1cf41ab832e6a082f4ef8a95c36#diff-c1129c8b045390789fa8ff62f2c6b4a9R30

**Comment by RamyRais** [comment]
yes now it works thank you. i see your solution is better than mine (y)
