### ISSUE TITLE
How to make 'post' requests? 

### ISSUE THREAD

**Issue by okayzed** [alubbe/named-routes#15]
How do you create post methods? I see app.get() and router.add('get', but don't see how for 'post'. Any tips / recommendations? 

I was using reversable router before, but the underlying module for reversable router has changed (xregexp.XRegExp has moved into the top level) and am trying to upgrade to named-routes instead. Thanks!

**Comment by RamyRais** [comment]
just put app.post it is app.METHOD(), where METHOD is one of the HTTP methods, such as GET, PUT, POST, and so on.

**Comment by alubbe** [comment]
Exactly, just replace "get" with "post" (or "put", or "delete", ...) in 
those examples.

**Comment by okayzed** [comment]
I meant to say: when I use router.post() and add('post'), the URL doesn't seem to work for me - the .get() and add('get') seem to work compatibly with my old calls to node-reversable-router, but .post and .add('post') do not resolve the old routes i had. 

I've forked node-reversable-router and fixed its issue (the XRegexp dependency stuff + toplevel import) and pinned my package.json to my github in the meanwhile.

**Comment by alubbe** [comment]
I've just added a test case for what I believe you are describing (registering a POST route and then trying to access it) @ https://github.com/alubbe/named-routes/commit/44a017d7bb66f795f0362770dc02e2c2add97915
It's working for me locally. Could you post a full example with code of what isn't working?

**Comment by alubbe** [comment]
@okayzed Are you still experiencing this issue?

**Comment by okayzed** [comment]
I don't know - I haven't checked in a while - please feel free to close /
delete the issue (deletion is preferable). Again, I forked the original
repo (reversable-router) and pointed my projects towards my forked repo.
