### ISSUE TITLE
Blueprints

### ISSUE THREAD

**Issue by lawli3t** [alubbe/named-routes#16]
Is it possible to use named-routes in blueprints too? I cant find a good example. I tried creating a Blueprint as a standalone (basically copied from the readme) and export the router but it didn't work.

**Comment by alubbe** [comment]
I'd love to help but I don't know what you mean by blueprint. Could you
please elaborate?

**Comment by lawli3t** [comment]
I'm sorry, i used the term im used to for flask. I mean routers in Express.js.

**Comment by alubbe** [comment]
Could you give me an example of what you are trying to write? Is it by any chance related to https://github.com/alubbe/named-routes/issues/13?

**Comment by alubbe** [comment]
@lawli3t any updates?

**Comment by lawli3t** [comment]
I'm sorry I'm answering this so late, but my team is fine with just coding the endpoints - so we dropped using named-routes. It doesn't matter that much for us anyways as it is just a one-time medium-sized student project.

Thanks for your efforts, I appreciate it a lot still.
