### ISSUE TITLE
Query parameters

### ISSUE THREAD

**Issue by grimurd** [alubbe/named-routes#19]
Does this module not support passing in query parameters?

**Comment by alubbe** [comment]
What do you mean, or what are you trying to achieve? You can use `build` to
generate the base url and then append the params to that url, and even use
something like the `url` package to generate it from an object.
Maybe you could post some code that shows what you are trying to achieve.

**Comment by grimurd** [comment]
If you've ever used UI-router for AngularJS then I was thinking it in the same way, they allow you to specify a query parameter in your routes(which are always optional) and populate them when building a url.

Example route:

/blog/:id?myQueryParam1&myQueryParam2

then in your code:

```javascript
url('blog', { id: 1, myQueryParam1: 'foo', myQueryParam2: 'bar' })
// => /blog/1?myQueryParam1=foo&myQueryParam2=bar
```

other example:

```javascript
url('blog', { id: 1, myQueryParam2: 'bar' })
// => /blog/1?myQueryParam2=bar
```

**Comment by alubbe** [comment]
No we do not support this right now. Is your use-case client-side or server-side?

**Comment by grimurd** [comment]
Server side. Just used ui-router as an example where I've used this before. But being able to create links with query parameters would be a nice addition. Adding URL queries dynamically in a server side template is definitely a valid use case. Of course you can always add the query by appending it to the output of the url builder method but I think the same could be said for parameters in some cases. I just think it would make the code a lot cleaner and more understandable if I could pass queries into the url build method.

**Comment by alubbe** [comment]
hey @grimurd 
that would be an interesting feature to add. You're welcome to contribute a PR.

**Comment by alubbe** [comment]
@grimurd Are you interested in contributing a PR? Otherwise I'd like to close this issue.
