### ISSUE TITLE
Question / Possible feature request

### ISSUE THREAD

**Issue by sashashakun** [alubbe/named-routes#20]
Hello! At first I want to say thank for your work!

I use this package in my project and have a question, is it possible to pass some params to template when I build route?

For example I have route:
```javascript
  app.get('/', 'home', (req, res) => {
    res.render('index', {someProp: 'some text'});
  });
```
And pass `someProp` to jade template.

Can I pass some prop when a use `named-routes` like this `app.namedRoutes.build('home')`?
May be something like: `app.namedRoutes.build('home', {oneMoreProp: 'some other text'})` and use `oneMoreProp` in template?

I will be glad if you could help me or give some advice, also ready to send PR if needed :)

**Comment by alubbe** [comment]
Hi @sashashakun 
Thanks for taking the time to open this issue. 
I believe such a feature goes too much against common practice in writing http protocols. You'll probably want the url to be the central point of all information and have jade extract its locals from something that the url infers. Remember also that the url could have been built on the client, where you have no way of changing the internals of your route implementation.
So in your case, I would instead use `app.namedRoutes.build('home') + "?oneMoreProp=foo"` and change your implementation to extract the GET parameter.

**Comment by sashashakun** [comment]
Thanks for answer, I think your advice about `app.namedRoutes.build('home') + "?oneMoreProp=foo"` will be good solution for my case.
