### ISSUE TITLE
Global Routes & Domains

### ISSUE THREAD

**Issue by Dexus** [alubbe/named-routes#21]
Hello,

is it possible, to share routes between 2 apps, that have a seperated vhost with a own app?

And second is it possible to add a support for absolute urls with the domain included?

**Comment by alubbe** [comment]
Yes that is supported. I have not tested it, however, so feel free to report back if anything is not working.

express, and by extension named-routes, have no awareness of the url that they hosted on. As a matter of fact, you are looking to reuse the same code for different hosts. If you want to generate absolute urls, it is recommended to write a helper function that builds on named-routes's url generator. One such way could be 
```js
var app = express();
router.extendExpress(app);
router.registerAppHelpers(app);

function buildAbsUrl(scheme, host, name, params, method) {
  return `${scheme}://${host}${app.namedRoutes.build(name, params, method)}`;
}

app.get('/admin/user/:id', 'admin.user.edit', function(req, res, next){
    var url = buildAbsUrl('https', 'example.com', 'admin.user.edit', {id: 2}); // https://example.com/admin/user/2
});

app.listen(3000);
```

**Comment by alubbe** [comment]
@Dexus if that cleared up your question, please close this issue. Thanks!

**Comment by alubbe** [comment]
Could you please post some code of a complete example and show me where it
fails? That would be tremendously helpful in figuring out what you're
looking for.

**Comment by alubbe** [comment]
@Dexus Any updates? Otherwise I'd like to close this issue.
