### ISSUE TITLE
Problems with Express 4 routes documentation

### ISSUE THREAD

**Issue by kokujin** [alubbe/named-routes#22]
ExpressJS 4s routes are created as follows: 

main.js
`````
var express = require('express');
var router = express.Router();

router.get('/', function(req, res, next) {
  res.render('index');
});

module.exports = router;
``````

The docs state the following code for Express 4 routes

`````
var searchRouter = express.Router();
router.extendExpress(searchRouter);
searchRouter.post('/users', 'users', function(){...});
app.use('/search', searchRouter);
`````
Which does not work.

Can some one point me to an example of working code?  or better still, add it here?

Thanks

**Comment by alubbe** [comment]
I am not sure what you mean by not working, since you are not proving any error messages.
If you are failing to access the route builder, you need to add `router.registerAppHelpers(app);`

Also, if possible, avoid the nesting of routers and just work the top-level hierachy as in this example https://github.com/alubbe/named-routes#as-a-replacement-for-express-framework-router

**Comment by kokujin** [comment]
Thanks. But what would really help me would be an example with the use case of an Express router. I declare my routes in separate route files as dictated my the ExpressJS generator. Maybe simple put, how do I retrofit something like this with named routes

``````
var express = require('express');
var router = express.Router();

router.get('/', function(req, res, next) {
  res.render('index');
});

module.exports = router;
```````

**Comment by alubbe** [comment]
Could you please provide me with a full example of what doesn't work? What about
```js
var express = require('express');
var router = express.Router();

var namedRoutes= require('named-routes');
new namedRoutes().extendExpress(router);

router.get('/', function(req, res, next) {
  res.render('index');
});

module.exports = router;
```

**Comment by kokujin** [comment]
Thanks @alubbe , sadly, you code above still does not work, and its even more confusing, for example this line

````
new namedRoutes().extendExpress(router);

its not being assigned to any variable or used anywhere
`````

or this According to the code you posted, this is still using the normal express router, which wont work

`````
router.get('/', function(req, res, next) { // <----- Original Express router
  res.render('index');
});

`````

Well I just tried it just in case and got this error

``````
(/home/kokujin/development/projects/ez-commerce/admin/views/partials/index.html) [Line 10, Column 8] Error: Unable to call `url`, which is undefined or falsey

``````

A working example would be really nice

**Comment by alubbe** [comment]
Hi @kokujin 
I am still confused about your enquiry. Are you sure want to use an instance of the express router instead of using the built-in one directly? Here is a working example:
```js
var express = require('express');
var router = express.Router();

var namedRoutes= require('named-routes');
new namedRoutes().extendExpress(router);

router.get('/bar', 'baz', function(req, res, next) {
  res.send('hello from ' + router.namedRoutes.build('baz'));
});

var app = express();
app.use('/foo', router);
app.listen(3000);
```
```
$ curl localhost:3000/foo/bar
hello from /bar
```
Please note that the built url does NOT contain '/foo'.
Here is what you could do with the built-in router:
```js
var express = require('express');
var app = express();

var namedRoutes= require('named-routes');
new namedRoutes().extendExpress(app);

app.get('/foo/bar', 'baz', function(req, res, next) {
  res.send('hello from ' + app.namedRoutes.build('baz'));
});

app.listen(3000);
```
```
$ curl localhost:3000/foo/bar
hello from /foo/bar
```

**Comment by kokujin** [comment]
Thanks for your patience.

I tried once again, here is an example:

Given a file called "index.js"

routes/index.js

`````
var express = require('express');
var router = express.Router();

var namedRoutes = require('named-routes');
new namedRoutes().extendExpress(router);

router.get('/bar', 'baz', function(req, res, next) {
  res.send('hello from ' + router.namedRoutes.build('baz'));
});

module.exports = router;
``````

Now, importing the exported route in another file called app.js
/app.js

``````
// Import routes
var routes = require('./routes/index');

// Mount routes
app.use('/', routes);
``````


I get a 404

**Comment by alubbe** [comment]
What about http://localhost:8000/dashboard/bar?

**Comment by kokujin** [comment]
I get 404s with:

 http://localhost:8000/dashboard/bar
 http://localhost:8000/bar

**Comment by kokujin** [comment]
My bad, it works now :).Thanks. The last thing, its usage in a template.

This fails

`````
{{ url('bar')}}
````

Is the url() function added to the app.locals object or does one have to do it manually?

**Comment by alubbe** [comment]
Try 
```js
new namedRoutes().extendExpress(router).registerAppHelpers(router);
```

**Comment by kokujin** [comment]
I got this:

``````
TypeError: Cannot set property 'url' of undefined
    at Router.registerAppHelpers (/home/kokujin/development/projects/test/node_modules/named-routes/router.js:153:28)
    at Object.<anonymous> (/home/kokujin/development/projects/test/routes/index.js:6:41)
`````````

**Comment by alubbe** [comment]
Sorry, that's because `registerAppHelpers` needs to be called with `app` rather than with `router`. Here is a working example:
```js
var express = require('express');
var router = express.Router();

var namedRoutes = require('named-routes');
var _router = new namedRoutes();
_router.extendExpress(router);

router.get('/bar', 'baz', function(req, res, next) {
  res.render('index', { title: 'Hey', message: 'Hello there!'});
});

var app = express();
_router.registerAppHelpers(app);
app.set('view engine', 'pug');
app.use('/foo', router);
app.listen(3000);
```
```pug
html
  head
    title= title
  body
    h1= message
    p= url("baz")
```
```
$ curl localhost:3000/foo/bar
<html><head><title>Hey</title></head><body><h1>Hello there!</h1><p>/bar</p></body></html>
```

**Comment by alubbe** [comment]
@kokujin if that cleared up your question, please close this issue. Thanks!

**Comment by kokujin** [comment]
Sorry for the delay @alubbe , I have'nt had the time to test  further, I'll get to it today. Thanks

**Comment by alubbe** [comment]
@kokujin Any updates? Otherwise I'd like to close this issue.

**Comment by kokujin** [comment]
Hi @alubbe, I'm sorry I forgot to mention that I decided to use "route-label" instead

[https://github.com/cermati/route-label](https://github.com/cermati/route-label-samplel)

I would try your library again sometime though. Thanks
