### ISSUE TITLE
Named routes are not shared among instances

### ISSUE THREAD

**Issue by harmenjanssen** [alubbe/named-routes#23]
Right now I can't easily split up my route configuration into multiple files – only the router that calls `registerAppHelpers()` makes its routes available to the app, but the app only lives in one spot, usually.

I have created a reduced test-case in this gist: https://gist.github.com/harmenjanssen/0b35bb6e20f254dba43fdf2878924131

There is an easy fix: make `routesByNameAndMethod` a property of `Router` instead of `this`. A static property if you will.   
I'm not sure wether you're interested in this change, since it alters the design of the module a bit. I'm more than happy to create a pull request to address this issue, but wanted to check with you first to see if you're interested at all.

Looking forward to your feedback!

**Comment by harmenjanssen** [comment]
By the way, I realised later that a simple solution could also be to create a sort of singleton `app.js` like this:

```javascript
'use strict';
const express = require('express');
let app;
if (!app) {
  app = express();
}

module.exports = app;
```

But still: having to call `registerAppHelpers(require('./app.js'))` in every routes configuration file is a bit repetitive.

**Comment by alubbe** [comment]
Splitting your routes into several files is a very good practice. However, global state is not - and that is what you would need for this instance https://gist.github.com/harmenjanssen/0b35bb6e20f254dba43fdf2878924131#file-index-js-L5 (which is responsible for the view engine and thus for the url helper) to communicate with this separate instance https://gist.github.com/harmenjanssen/0b35bb6e20f254dba43fdf2878924131#file-routes-js-L7 through named-routes.

Instead, you should wire them up by passing `app` from index.js to routes.js. I.e., change routes.js to export a `function(app){}` and avoid creating a new named-routes instance.

**Comment by harmenjanssen** [comment]
Yes, I guess you're right!  
I will refactor accordingly. Thanks for a quick response!
