### ISSUE TITLE
routes unit testing

### ISSUE THREAD

**Issue by asmodehn** [alubbe/named-routes#29]
I would like to use named-routes with restify, as well as with express.
I am guessing to get it working with restify is not such a big deal (I ll investigate that sometime soon)

But from this, derive the issue to unit test these routes independently of the server they are running on...
Is there any documentation / example I can follow in order to do this ? (I am currently using mocha with supertest)

Thanks !

**Comment by alubbe** [comment]
Hi @asmodehn 
Could you post an example of the kind of unit tests that you are looking to write? 
You can probably use the standalone-mode (https://github.com/alubbe/named-routes#as-a-standalone) to create routes and test them in-memory without creating http requests.

**Comment by asmodehn** [comment]
Hi @alubbe,

I have little experience in writing web backend in nodejs. I come from the
python world (mostly using flask to be precise)...
In my very recent endeavors to implement a web backend with nodejs I have
been browsing around to find libraries that would help me structure my
code, while providing flexibility, in a way that I am used to with flask...

I found named-routes to be very useful to have flexible urls construct
(same as flask's endpoint concept).
Flask allows to test them directly with a specific configuration of the
main app... This helps tracking errors with a debugger, get cleaner
traceback, etc.

I m not sure if it would be as useful in js, or if named-routes is even a
good place for this.

I ll see if I can come up with some js example code when I get some time...

Cheers !

--
AlexV
