### ISSUE TITLE
named-routes on client side

### ISSUE THREAD

**Issue by Dattaya** [alubbe/named-routes#8]
Hi, @alubbe. Thank you for this library. Could you tell if it's possible somehow to use this library on the client side via webpack or browserify without exposing the code of the routes. I have a strong feeling that it's not possible. I guess I should create a `match` function that takes a route name and params object and some utility that on `npm run build` creates a file with an object of route names and corresponding strings. Maybe you can give some advice on how to implement it.

**Comment by alubbe** [comment]
I'm not sure I fully understand what you are looking for. By 'code of the routes', do mean the mapping of names to routes, like 'admin.user.edit' maps to '/admin/user/:id'?
In general all logic that the client side is capable of doing without ajax requests can be read and is thus exposed. Strings, such as route names, are also never obfuscated by minifiers.
If this is what you meant, then it is indeed impossible for any library to do this.

**Comment by Dattaya** [comment]
Thank you for the answer! By the code of the routes I mean a body of each route, e.g.:

```javascript
app.get('/admin/user/:id', function(req, res, next){
    // body of the route
});
```

I'll try to use it with webpack and will see which files have been exported to the final `bundle.js`. Thanks again. Closing this issue for now.

**Comment by alubbe** [comment]
Those lines of code live in your server-side app, don't they? Webpack will not bundle that and thus, your code should be safe.
