### ISSUE TITLE
Check which route is currently active

### ISSUE THREAD

**Issue by Sk1Zy** [alubbe/named-routes#9]
I want to have a function that tells me if a given route is active. So i can for example control which menu item gets the css class "active".

Any way to achieve this with named-routes?

**Comment by alubbe** [comment]
Yes, that information resides in the request object, specifically as the name property of the request's route `req.route.name`
```js
function(req, res, next) {
  console.log(req.route.name);
};
```
This will either be the name of your route or `undefined`. You can take that and pass it into your view as a local variable.

**Comment by Sk1Zy** [comment]
Thanks, works like a charm :+1:
